config/routes.rb
Rails.application.routes.draw do
  get '/templates/:path.html' => 'templates#template', constraints: { path: /.+/ }
  
  scope '/api' do
    resources :connections
  
    resources :notices, :only => [:list] do
      collection do
        get 'list'
      end
    end
  
    resources :notifications, :only => [:delete] do
      collection do
        get 'list'
        delete 'delete'
      end
    end
  
    resources :item_proposes, :only => [:show, :create]
  
    resources :messages, :only => [:list, :create] do
      collection do
        get 'list'
        post 'propose'
      end
    end
  
    resources :item_favorites, :only => [:create]
  
   resources :users, :only => [:show, :login, :mypage, :list, :logout, :create, :update_user, :upload] do
      collection do
        get 'list'
        get 'login'
        get 'logout'
        get 'mypage'
        get 'mail_auth'
        put 'update_user'
        post 'upload'
      end
    end
  
    resources :item_comments, :only => [:list, :create] do
      collection do
        get 'list'
      end
    end
  
    resources :items, :only => [:index, :show, :list, :detail, :entry, :create] do
      collection do
        get 'index'
        get 'list'
        get 'detail'
        get 'entry'
      end
    end
    
  end

  get '/work' => 'templates#index'
  get '/message' => 'templates#index'
  get '/message/:id' => 'templates#index'
  get '/message/target/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/work/detail/:id' => 'templates#index'
  get '/mypage' => 'templates#index'
  get '/mypage/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/connection' => 'templates#index'
  get '/privacypolicy' => 'templates#index'
  get '/agreement' => 'templates#index'
  

  root 'layouts#index'

end

app/models/item_favorite.rb
class ItemFavorite < ActiveRecord::Base
end

app/controllers/item_favorites_controller.rb
class ItemFavoritesController < ApplicationController
  before_action :set_item_favorite, only: [:show, :edit, :update, :destroy]

  # GET /item_favorites
  # GET /item_favorites.json
  def index
  end

  # GET /item_favorites/1
  # GET /item_favorites/1.json
  def show
  end

  # GET /item_favorites/new
  def new
  end

  # GET /item_favorites/1/edit
  def edit
  end

  # POST /item_favorites
  # POST /item_favorites.json
  def create
    ret = check_logined
    if !ret 
      return
    end
    
    item = Item.find(params[:item_id])
    if item[:favorite_count].blank?
      item[:favorite_count] = 0
    end

    ActiveRecord::Base.transaction do

      if params[:flg] == "0"
        # 追加処理
        @item_favorite = ItemFavorite.new()
        @item_favorite[:item_id] = params[:item_id]
        set_create_user_id(@item_favorite)
        
        if !@item_favorite.save
          render :json => @item_favorite.errors, status: :unprocessable_entity
          raise ActiveRecord::Rollback
        end
        
        item[:favorite_count] = item[:favorite_count] + 1
        item.save
        
      else
        # 削除処理
        @item_favorite = ItemFavorite.find_by(["item_id = ? and create_user_id = ?", params[:item_id], session[:user_id]])
        @item_favorite.destroy

        item[:favorite_count] = item[:favorite_count] - 1
        item.save
      end
      
      # つながり追加処理
      connection = Connection.new()
      if params[:flg] == "0"
        connection[:connect_kbn] = 11
      else
        connection[:connect_kbn] = 13
      end
      connection[:from_user_id] = session[:user_id]
      connection[:to_user_id] = item[:create_user_id]
      connection[:target_id] =  @item_favorite[:item_id]
      set_create_user_id(connection)
      if is_find_connect_to_user(connection[:from_user_id], connection[:to_user_id])
        connection[:new_flg] = 1
      end
      if !connection.save
        render :json => connection.errors, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end

      connection = Connection.new()
      if params[:flg] == "0"
        connection[:connect_kbn] = 12
      else
        connection[:connect_kbn] = 14
      end
      connection[:from_user_id] = item[:create_user_id]
      connection[:to_user_id] = session[:user_id]
      connection[:target_id] =  @item_favorite[:item_id]
      set_create_user_id(connection)
      if is_find_connect_to_user(connection[:from_user_id], connection[:to_user_id])
        connection[:new_flg] = 1
      end
      if !connection.save
        render :json => connection.errors, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end      
      
      render :json => ""
    end
    
    return

  rescue => ex
    logger.fatal controller_name + " " + action_name + " " + ex.message
    errors = Hash.new
    errors[:error_message] = Array.new(1, "予期せぬエラーが発生しました。")
    render :json => errors, status: :unprocessable_entity
    
  end

  # PATCH/PUT /item_favorites/1
  # PATCH/PUT /item_favorites/1.json
  def update
  end

  # DELETE /item_favorites/1
  # DELETE /item_favorites/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_favorite
      @item_favorite = ItemFavorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_favorite_params
      params.require(:item_favorite).permit(:item_id, :create_user_id, :update_user_id)
    end
end

app/helpers/item_favorites_helper.rb
module ItemFavoritesHelper
end

app/views/item_favorites/_form.html.erb
<%= form_for(@item_favorite) do |f| %>
  <% if @item_favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_favorite.errors.count, "error") %> prohibited this item_favorite from being saved:</h2>

      <ul>
      <% @item_favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :create_user_id %><br>
    <%= f.number_field :create_user_id %>
  </div>
  <div class="field">
    <%= f.label :update_user_id %><br>
    <%= f.number_field :update_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_favorites/edit.html.erb
<h1>Editing Item Favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_favorite %> |
<%= link_to 'Back', item_favorites_path %>

app/views/item_favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Favorites</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th>Create user</th>
      <th>Update user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_favorites.each do |item_favorite| %>
      <tr>
        <td><%= item_favorite.item_id %></td>
        <td><%= item_favorite.user_id %></td>
        <td><%= item_favorite.create_user_id %></td>
        <td><%= item_favorite.update_user_id %></td>
        <td><%= link_to 'Show', item_favorite %></td>
        <td><%= link_to 'Edit', edit_item_favorite_path(item_favorite) %></td>
        <td><%= link_to 'Destroy', item_favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item favorite', new_item_favorite_path %>

app/views/item_favorites/new.html.erb
<h1>New Item Favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', item_favorites_path %>

app/views/item_favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_favorite.item_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @item_favorite.user_id %>
</p>

<p>
  <strong>Create user:</strong>
  <%= @item_favorite.create_user_id %>
</p>

<p>
  <strong>Update user:</strong>
  <%= @item_favorite.update_user_id %>
</p>

<%= link_to 'Edit', edit_item_favorite_path(@item_favorite) %> |
<%= link_to 'Back', item_favorites_path %>