config/routes.rb
Rails.application.routes.draw do
  get '/templates/:path.html' => 'templates#template', constraints: { path: /.+/ }
  
  scope '/api' do
    resources :connections
  
    resources :notices, :only => [:list] do
      collection do
        get 'list'
      end
    end
  
    resources :notifications, :only => [:delete] do
      collection do
        get 'list'
        delete 'delete'
      end
    end
  
    resources :item_proposes, :only => [:show, :create]
  
    resources :messages, :only => [:list, :create] do
      collection do
        get 'list'
        post 'propose'
      end
    end
  
    resources :item_favorites, :only => [:create]
  
   resources :users, :only => [:show, :login, :mypage, :list, :logout, :create, :update_user, :upload] do
      collection do
        get 'list'
        get 'login'
        get 'logout'
        get 'mypage'
        get 'mail_auth'
        put 'update_user'
        post 'upload'
      end
    end
  
    resources :item_comments, :only => [:list, :create] do
      collection do
        get 'list'
      end
    end
  
    resources :items, :only => [:index, :show, :list, :detail, :entry, :create] do
      collection do
        get 'index'
        get 'list'
        get 'detail'
        get 'entry'
      end
    end
    
  end

  get '/work' => 'templates#index'
  get '/message' => 'templates#index'
  get '/message/:id' => 'templates#index'
  get '/message/target/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/work/detail/:id' => 'templates#index'
  get '/mypage' => 'templates#index'
  get '/mypage/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/connection' => 'templates#index'
  get '/privacypolicy' => 'templates#index'
  get '/agreement' => 'templates#index'
  

  root 'layouts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/connection.rb
class Connection < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :work_kbn, presence: { message: 'を選択してください。'}
  validates :payment_kbn, presence: { message: 'を選択してください。'}
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 999999999 }, if: :payment_kbn_project?
  validates :noki, presence: true, if: :payment_kbn_project?
  validates :hour_price_kbn, presence: { message: 'を選択してください。'}, if: :payment_kbn_hour?
  validates :week_hour_kbn, presence: { message: 'を選択してください。'}, if: :payment_kbn_hour?
  validates :week_hour_period_kbn, presence: { message: 'を選択してください。'}, if: :payment_kbn_hour?
#  validate :limit_date_is_valid_datetime
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 3000 }
  validates :limit_date, presence: true

  def payment_kbn_project?
    payment_kbn == 2
  end

  def payment_kbn_hour?
    payment_kbn == 1
  end
  
  def limit_date_is_valid_datetime
    #errors.add(:limit_date, 'の日付の形式が不正です(YYYY-MM-DD)') if (!limit_date.blank? && (DateTime.parse(limit_date) rescue ArgumentError) == ArgumentError)
    
    # return if limit_date.blank?
#     
    # if limit_date != 8
      # errors.add(:noki, "の日付の値が不正です(YYYY-MM-DD)")
      # return
    # end
#  
    # y = limit_date[0, 4].to_i
    # m = limit_date[5, 2].to_i
    # d = limit_date[7, 2].to_i
    # unless Date.valid_date?(y, m, d)
      # errors.add(:limit_date, "の日付の値が不正です(YYYY-MM-DD)")
    # end      
    
  end
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
end

app/models/item_comment.rb
class ItemComment < ActiveRecord::Base
  validates :comment, presence: true, length: { maximum: 2000 }
end

app/models/item_favorite.rb
class ItemFavorite < ActiveRecord::Base
end

app/models/item_good.rb
class ItemGood < ActiveRecord::Base
end

app/models/item_propose.rb
class ItemPropose < ActiveRecord::Base
  validates :payment_kbn, presence: { message: 'を選択してください。'}
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 999999999 }, if: :payment_kbn_project?
  validates :noki, presence: true, if: :payment_kbn_project?
  validates :hour_price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 99999 }, if: :payment_kbn_hour?
  validates :week_hour_kbn, presence: { message: 'を選択してください。'}, if: :payment_kbn_hour?
  validates :week_hour_period_kbn, presence: { message: 'を選択してください。'}, if: :payment_kbn_hour?
  validates :content, presence: true, length: { maximum: 3000 }

  def payment_kbn_project?
    payment_kbn == 122
  end

  def payment_kbn_hour?
    payment_kbn == 121
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 50 }, if: :parent_message?
  validates :content, presence: true, length: { maximum: 3000 }
  
  def parent_message?
    parent_id == 0
  end
  
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 255 }, if: :new_regist?
   validates_uniqueness_of :email, :message => 'はすでに登録されています。'
   VALID_PASS_REGEX = /[0-9].*[a-zA-Z]|[a-zA-Z].*[0-9]/
   validates :password, presence: true, length: { in: 6..15 }
   validates :password, format: { with: VALID_PASS_REGEX, message: 'は半角英数混在で入力してください' }
   VALID_NAME_REGEX = /[a-z\d\-.]/
   validates :display_name, presence: true, length: { in: 4..10 }
   validate :display_name_valid
#   validates :display_name, format: { with: VALID_NAME_REGEX, message: 'は半角英数、(記号「@_-」)で入力してください' }
   
  def new_regist?
    if (id.nil? || id == 0) 
      return true
    else
      return false
    end
  end
  
  def check_user_password
     
  end
  
  def display_name_valid()
    if !(/\A[A-Za-z]+\z/ =~ display_name.gsub(/[0-9@_-]/,""))
      errors.add(:display_name, "は半角英数、記号「@_-」で入力してください(数字、記号のみは不可)")
    end
  end
   
end

app/models/user_work_category.rb
class UserWorkCategory < ActiveRecord::Base
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/list
  def list

    cond = Hash.new
    if session[:user_id].nil?
      cond[:user_id] = session[:user_id]
    else
      cond[:user_id] = -99999
    end

    # 通知タイトル一覧の取得
    sql = ""
    sql += "select ns.id "
    sql += "      ,ns.title "
    sql += "      ,ns.content "
    sql += "      ,'' AS created_at_str "
    sql += '      ,ns.created_at '
    sql += "      ,nt_msg.nt_count notification_inf_count "
    sql += "from notices ns "
    sql += "left join (select count(nt.user_id) nt_count, "
    sql += "                  nt.user_id, "
    sql += "                  nt.target_id "
    sql += "           from notifications nt "
    sql += "           where nt.user_id = :user_id "
    sql += "           and nt.notification_kbn = 2 "
    sql += "           group by nt.user_id "
    sql += "                   ,nt.target_id) nt_msg "
    sql += "on nt_msg.target_id = ns.id "
    sql += "order by ns.created_at desc "
    notices = Notice.find_by_sql([sql, cond])    
    
    if notices.nil? || notices.size == 0
      render :json => ""
      return;
    end
    
    for notice in notices do
      notice[:created_at_str] = notice[:created_at].strftime("%Y/%m/%d %H:%M:%S")
    end
    
    render :json => notices
  end

  # GET /notices/new
  def new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :content, :create_user_id, :update_user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_goods_helper.rb
module ItemGoodsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :create_user_id %><br>
    <%= f.number_field :create_user_id %>
  </div>
  <div class="field">
    <%= f.label :update_user_id %><br>
    <%= f.number_field :update_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Create user</th>
      <th>Update user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.content %></td>
        <td><%= notice.create_user_id %></td>
        <td><%= notice.update_user_id %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<p>
  <strong>Create user:</strong>
  <%= @notice.create_user_id %>
</p>

<p>
  <strong>Update user:</strong>
  <%= @notice.update_user_id %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>