config/routes.rb
Rails.application.routes.draw do
  get '/templates/:path.html' => 'templates#template', constraints: { path: /.+/ }
  
  scope '/api' do
    resources :connections
  
    resources :notices, :only => [:list] do
      collection do
        get 'list'
      end
    end
  
    resources :notifications, :only => [:delete] do
      collection do
        get 'list'
        delete 'delete'
      end
    end
  
    resources :item_proposes, :only => [:show, :create]
  
    resources :messages, :only => [:list, :create] do
      collection do
        get 'list'
        post 'propose'
      end
    end
  
    resources :item_favorites, :only => [:create]
  
   resources :users, :only => [:show, :login, :mypage, :list, :logout, :create, :update_user, :upload] do
      collection do
        get 'list'
        get 'login'
        get 'logout'
        get 'mypage'
        get 'mail_auth'
        put 'update_user'
        post 'upload'
      end
    end
  
    resources :item_comments, :only => [:list, :create] do
      collection do
        get 'list'
      end
    end
  
    resources :items, :only => [:index, :show, :list, :detail, :entry, :create] do
      collection do
        get 'index'
        get 'list'
        get 'detail'
        get 'entry'
      end
    end
    
  end

  get '/work' => 'templates#index'
  get '/message' => 'templates#index'
  get '/message/:id' => 'templates#index'
  get '/message/target/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/work/detail/:id' => 'templates#index'
  get '/mypage' => 'templates#index'
  get '/mypage/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/connection' => 'templates#index'
  get '/privacypolicy' => 'templates#index'
  get '/agreement' => 'templates#index'
  

  root 'layouts#index'

end

app/controllers/item_proposes_controller.rb
class ItemProposesController < ApplicationController
  before_action :set_item_propose, only: [:show, :edit, :update, :destroy]

  # GET /item_proposes
  # GET /item_proposes.json
  def index
  end

  # GET /item_proposes/1
  # GET /item_proposes/1.json
  def show
    
    ret = check_logined
    if !ret 
      return
    end
    
    cond = Hash.new
    cond[:item_id] = params[:id]
    cond[:user_id] = session[:user_id]

    # sqlセット
    sql = ""
    sql += "select itp.* "
    sql += "      ,ifnull(nm_week_hour_kbn.name, '') week_hour_kbn_nm "
    sql += "      ,ifnull(nm_week_hour_period_kbn.name, '') week_hour_period_kbn_nm "
    sql += "from item_proposes itp "
    sql += "left join names nm_week_hour_kbn "
    sql += "on nm_week_hour_kbn.id = itp.week_hour_kbn "
    sql += "left join names nm_week_hour_period_kbn "
    sql += "on nm_week_hour_period_kbn.id = itp.week_hour_period_kbn "
    sql += "where itp.item_id = :item_id "
    sql += "and itp.create_user_id = :user_id "
    
    # 検索してデータをjsonで返す
    itemPropose = ItemPropose.find_by_sql([sql, cond])  
    if itemPropose.nil? || itemPropose.size == 0 
      render :json => ""
    else
      render :json => itemPropose[0]
    end
  end

  # GET /item_proposes/new
  def new
  end

  # GET /item_proposes/1/edit
  def edit
  end

  # POST /item_proposes
  # POST /item_proposes.json
  def create
    
    isErrorFlg = false
    
    ret = check_logined
    if !ret 
      return
    end
    
    item_propose_param = ItemPropose.new(item_propose_params)
    
    @item_propose = nil
    if !params[:id].blank?
      @item_propose = ItemPropose.find(params[:id])
    else
      @item_propose = item_propose_param
    end
    
    set_create_user_id(@item_propose)

    ActiveRecord::Base.transaction do
      # 提案対象アイテム取得
      item = Item.find(@item_propose[:item_id])

      # 提案保存処理
      if params[:id].blank?
        # 提案件数インクリメント
        if item[:propose_count].blank?
          item[:propose_count] = 0
        end
        item[:propose_count] = item[:propose_count] + 1
        item.save

        if !@item_propose.save
          render :json => @item_propose.errors, status: :unprocessable_entity
          raise ActiveRecord::Rollback
        end
      else
        item_propose = ItemPropose.find(params[:id])
        if !item_propose[:ok_flg].blank? && item_propose[:ok_flg] == 1
          errors = Hash.new
          errors[:error_message] = Array.new(1, "すでに合意済みの提案です。")
          render :json => errors, status: :unprocessable_entity
          raise ActiveRecord::Rollback
        end
        
        if !@item_propose.update(item_propose_params)
          render :json => @item_propose.errors, status: :unprocessable_entity
          raise ActiveRecord::Rollback
        end
      end
      
      # メッセージ追加処理
      message = Message.new()
      message[:item_id] = @item_propose[:item_id]
      message[:parent_id] = 0
      message[:send_user_id] = session[:user_id]
      message[:receive_user_id] = item[:create_user_id]
      message[:title] = item[:title]
      message[:content] = @item_propose[:content]
      set_create_user_id(message)
      if !message.save
        render :json => message.errors, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end
      
      # つながり追加処理
      connection = Connection.new()
      if params[:id].blank?
        connection[:connect_kbn] = 3
      else
        connection[:connect_kbn] = 9
      end
      connection[:from_user_id] = session[:user_id]
      connection[:to_user_id] = item[:create_user_id]
      connection[:target_id] =  @item_propose[:item_id]
      set_create_user_id(connection)
      if is_find_connect_to_user(connection[:from_user_id], connection[:to_user_id])
        connection[:new_flg] = 1
      end
      if !connection.save
        render :json => connection.errors, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end

      connection = Connection.new()
      if params[:id].blank?
        connection[:connect_kbn] = 4
      else
        connection[:connect_kbn] = 10
      end
      connection[:from_user_id] = item[:create_user_id]
      connection[:to_user_id] = session[:user_id]
      connection[:target_id] =  @item_propose[:item_id]
      set_create_user_id(connection)
      if is_find_connect_to_user(connection[:from_user_id], connection[:to_user_id])
        connection[:new_flg] = 1
      end
      if !connection.save
        render :json => connection.errors, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end
      
      fromUser = User.find(message[:send_user_id])
      toUser = User.find(message[:receive_user_id])
      
      # 通知追加
      notification = Notification.new()
      notification[:notification_kbn] = 1;
      notification[:target_id] = message[:id];
      notification[:user_id] = message[:receive_user_id];
      set_create_user_id(notification)
      if !notification.save
        render :json => notification.errors, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end
      
      # メッセージ送信処理
      linkUrl = request.url.gsub("api/item_proposes", "")
      content = message[:content]
      if message[:content].length > 3
        content = message[:content][0, (message[:content].length - 3)] + "..."
      end
      
      @mail = PostMailer.notice_proposes(fromUser[:email], toUser[:email], fromUser[:display_name], toUser[:display_name], message[:title], content, linkUrl)
      @mail.deliver_now # if Rails.env.production?

      render :json => @item_propose
    end
    
    return

  rescue => ex
    logger.fatal controller_name + " " + action_name + " " + ex.message
    errors = Hash.new
    errors[:error_message] = Array.new(1, "予期せぬエラーが発生しました。")
    render :json => errors, status: :unprocessable_entity
    
  end

  # PATCH/PUT /item_proposes/1
  # PATCH/PUT /item_proposes/1.json
  def update
  end

  # DELETE /item_proposes/1
  # DELETE /item_proposes/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_propose
#      @item_propose = ItemPropose.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_propose_params
      params.require(:item_propose).permit(:item_id, :payment_kbn, :price, :noki, :hour_price, :week_hour_kbn, :week_hour_period_kbn, :content, :create_user_id, :update_user_id)
    end
end

app/helpers/item_proposes_helper.rb
module ItemProposesHelper
end

app/views/item_proposes/_form.html.erb
<%= form_for(@item_propose) do |f| %>
  <% if @item_propose.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_propose.errors.count, "error") %> prohibited this item_propose from being saved:</h2>

      <ul>
      <% @item_propose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :payment_kbn %><br>
    <%= f.number_field :payment_kbn %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :noki %><br>
    <%= f.date_select :noki %>
  </div>
  <div class="field">
    <%= f.label :hour_price_kbn %><br>
    <%= f.number_field :hour_price_kbn %>
  </div>
  <div class="field">
    <%= f.label :week_hour_kbn %><br>
    <%= f.number_field :week_hour_kbn %>
  </div>
  <div class="field">
    <%= f.label :week_hour_period_kbn %><br>
    <%= f.number_field :week_hour_period_kbn %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :create_user_id %><br>
    <%= f.number_field :create_user_id %>
  </div>
  <div class="field">
    <%= f.label :update_user_id %><br>
    <%= f.number_field :update_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_proposes/edit.html.erb
<h1>Editing Item Propose</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_propose %> |
<%= link_to 'Back', item_proposes_path %>

app/views/item_proposes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Proposes</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Payment kbn</th>
      <th>Price</th>
      <th>Noki</th>
      <th>Hour price kbn</th>
      <th>Week hour kbn</th>
      <th>Week hour period kbn</th>
      <th>Content</th>
      <th>Create user</th>
      <th>Update user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_proposes.each do |item_propose| %>
      <tr>
        <td><%= item_propose.item_id %></td>
        <td><%= item_propose.payment_kbn %></td>
        <td><%= item_propose.price %></td>
        <td><%= item_propose.noki %></td>
        <td><%= item_propose.hour_price_kbn %></td>
        <td><%= item_propose.week_hour_kbn %></td>
        <td><%= item_propose.week_hour_period_kbn %></td>
        <td><%= item_propose.content %></td>
        <td><%= item_propose.create_user_id %></td>
        <td><%= item_propose.update_user_id %></td>
        <td><%= link_to 'Show', item_propose %></td>
        <td><%= link_to 'Edit', edit_item_propose_path(item_propose) %></td>
        <td><%= link_to 'Destroy', item_propose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item propose', new_item_propose_path %>

app/views/item_proposes/new.html.erb
<h1>New Item Propose</h1>

<%= render 'form' %>

<%= link_to 'Back', item_proposes_path %>

app/views/item_proposes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_propose.item_id %>
</p>

<p>
  <strong>Payment kbn:</strong>
  <%= @item_propose.payment_kbn %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item_propose.price %>
</p>

<p>
  <strong>Noki:</strong>
  <%= @item_propose.noki %>
</p>

<p>
  <strong>Hour price kbn:</strong>
  <%= @item_propose.hour_price_kbn %>
</p>

<p>
  <strong>Week hour kbn:</strong>
  <%= @item_propose.week_hour_kbn %>
</p>

<p>
  <strong>Week hour period kbn:</strong>
  <%= @item_propose.week_hour_period_kbn %>
</p>

<p>
  <strong>Content:</strong>
  <%= @item_propose.content %>
</p>

<p>
  <strong>Create user:</strong>
  <%= @item_propose.create_user_id %>
</p>

<p>
  <strong>Update user:</strong>
  <%= @item_propose.update_user_id %>
</p>

<%= link_to 'Edit', edit_item_propose_path(@item_propose) %> |
<%= link_to 'Back', item_proposes_path %>