config/routes.rb
Rails.application.routes.draw do
  get '/templates/:path.html' => 'templates#template', constraints: { path: /.+/ }
  
  scope '/api' do
    resources :connections
  
    resources :notices, :only => [:list] do
      collection do
        get 'list'
      end
    end
  
    resources :notifications, :only => [:delete] do
      collection do
        get 'list'
        delete 'delete'
      end
    end
  
    resources :item_proposes, :only => [:show, :create]
  
    resources :messages, :only => [:list, :create] do
      collection do
        get 'list'
        post 'propose'
      end
    end
  
    resources :item_favorites, :only => [:create]
  
   resources :users, :only => [:show, :login, :mypage, :list, :logout, :create, :update_user, :upload] do
      collection do
        get 'list'
        get 'login'
        get 'logout'
        get 'mypage'
        get 'mail_auth'
        put 'update_user'
        post 'upload'
      end
    end
  
    resources :item_comments, :only => [:list, :create] do
      collection do
        get 'list'
      end
    end
  
    resources :items, :only => [:index, :show, :list, :detail, :entry, :create] do
      collection do
        get 'index'
        get 'list'
        get 'detail'
        get 'entry'
      end
    end
    
  end

  get '/work' => 'templates#index'
  get '/message' => 'templates#index'
  get '/message/:id' => 'templates#index'
  get '/message/target/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/work/detail/:id' => 'templates#index'
  get '/mypage' => 'templates#index'
  get '/mypage/:id' => 'templates#index'
  get '/employer/:id' => 'templates#index'
  get '/connection' => 'templates#index'
  get '/privacypolicy' => 'templates#index'
  get '/agreement' => 'templates#index'
  

  root 'layouts#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end
  
  def list
    
    if session[:user_id].blank?
      render :json => ""
      return
    end

    cond = Hash.new
    cond[:user_id] = session[:user_id]

    sql = ""
    sql += "select ifnull(nt_msg.nt_count, 0) notification_msg_count"
    sql += "      ,ifnull(nt_inf.nt_count, 0) notification_inf_count"
    sql += "  from users ur "
    sql += "  left join (select count(nt.id) nt_count, "
    sql += "                    nt.user_id  "
    sql += "             from notifications nt "
    sql += "             where nt.user_id = :user_id "
    sql += "             and nt.notification_kbn = 1 "
    sql += "             group by nt.user_id) nt_msg "
    sql += "  on nt_msg.user_id = ur.id "
    sql += "  left join (select count(nt.id) nt_count, "
    sql += "                    nt.user_id  "
    sql += "             from notifications nt "
    sql += "             where nt.user_id = :user_id "
    sql += "             and nt.notification_kbn = 2 "
    sql += "             group by nt.user_id) nt_inf "
    sql += "  on nt_inf.user_id = ur.id "
    sql += "  where ur.id = :user_id "
    
    # 検索
    users = User.find_by_sql([sql, cond])    
    
    render :json => users[0]

  end

  # GET /notifications/new
  def new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def delete
    
    cond = Hash.new
    cond[:id] = params[:id]
    cond[:kbn] = params[:kbn]
    cond[:user_id] = session[:user_id]

    ActiveRecord::Base.transaction do
      
      if params[:kbn].to_i == 1
        # メッセージ
        sql = ""
        sql += "select * "
        sql += "from messages "
        sql += "where (id = :id or parent_id = :id) "
        messages = Message.find_by_sql([sql, cond])  
        
        if messages.nil? || messages.size == 0
          render :json => ""
          return
        end
        
        for message in messages do
          cond[:id] = message[:id]

          sql = ""
          sql += "select * "
          sql += "from notifications "
          sql += "where target_id = :id "
          sql += "and user_id = :user_id "
          sql += "and notification_kbn = :kbn "
          notifications = Notification.find_by_sql([sql, cond])  
          
          if notifications.nil? || notifications.size == 0
            next
          end
          
          for notification in notifications do
            notification.destroy!
          end
        end        
        
      else
        # お知らせ
        sql = ""
        sql += "select * "
        sql += "from notifications "
        sql += "where target_id = :id "
        sql += "and user_id = :user_id "
        sql += "and notification_kbn = :kbn "
        notifications = Notification.find_by_sql([sql, cond])  
        
        if notifications.nil? || notifications.size == 0
          render :json => ""
          return
        end
        
        for notification in notifications do
          notification.destroy!
        end
      end

      render :json => ""

    end

    return

  rescue => ex
    logger.fatal controller_name + " " + action_name + " " + ex.message
    errors = Hash.new
    errors[:error_message] = Array.new(1, "予期せぬエラーが発生しました。")
    render :json => errors, status: :unprocessable_entity
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      #@notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:notification_kbn, :target_id, :user_id, :create_user_id, :update_user_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notification_kbn %><br>
    <%= f.number_field :notification_kbn %>
  </div>
  <div class="field">
    <%= f.label :target_id %><br>
    <%= f.number_field :target_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :create_user_id %><br>
    <%= f.number_field :create_user_id %>
  </div>
  <div class="field">
    <%= f.label :update_user_id %><br>
    <%= f.number_field :update_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Notification kbn</th>
      <th>Target</th>
      <th>User</th>
      <th>Create user</th>
      <th>Update user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.notification_kbn %></td>
        <td><%= notification.target_id %></td>
        <td><%= notification.user_id %></td>
        <td><%= notification.create_user_id %></td>
        <td><%= notification.update_user_id %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notification kbn:</strong>
  <%= @notification.notification_kbn %>
</p>

<p>
  <strong>Target:</strong>
  <%= @notification.target_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>Create user:</strong>
  <%= @notification.create_user_id %>
</p>

<p>
  <strong>Update user:</strong>
  <%= @notification.update_user_id %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>